"""Domain-specific exception hierarchy. Sprint 11 adds ToolRegistryError, ToolNotFoundError, ToolAlreadyRegisteredError."""

from nikola.domain.errors.domain_errors import (
    BrainError,
    CircularDependencyError,
    CommandExecutionError,
    ConfigFileNotFoundError,
    ConfigurationError,
    ConfigValidationError,
    ConversationError,
    ExecutionError,
    InvalidCommandError,
    MemoryError,
    MessageValidationError,
    NikolaError,
    PlanningError,
    ServiceNotRegisteredError,
    ToolAlreadyRegisteredError,
    ToolNotFoundError,
    ToolRegistryError,
    ToolUnavailableError,
)

__all__ = [
    "NikolaError",
    "ConfigurationError",
    "ConfigFileNotFoundError",
    "ConfigValidationError",
    "InvalidCommandError",
    "ToolUnavailableError",
    "CommandExecutionError",
    "ServiceNotRegisteredError",
    "CircularDependencyError",
    "BrainError",
    "ConversationError",
    "MessageValidationError",
    "MemoryError",
    "PlanningError",
    "ExecutionError",
    "ToolRegistryError",
    "ToolNotFoundError",
    "ToolAlreadyRegisteredError",
]
